### ISSUE TITLE
Not working with *.ies files

### ISSUE THREAD

**Issue by pedrobullo** [r1emu/IPFUnpacker#1]
"Done!" but doesn't change any file. Files Ok. Permissions Ok.
System: Windows 10 / 64

**Comment by Spl3en** [comment]
Could you try with the last version? I've just added additional checks in https://github.com/r1emu/IPFUnpacker/commit/45eda6dba255cbc6a676ccc256fb3b70f0ac7907
Make sure the game isn't launched when you decrypt the files.

**Comment by pedrobullo** [comment]
I'm trying to get all *.ies files. Tried with Cygwin and CMD. It seems that is not replacing the files even running as admin and givin' all permissions.

**Comment by Spl3en** [comment]
It should work with CMD unmodified.
I've [forced the call to FlushViewOfFile](https://github.com/r1emu/IPFUnpacker/commit/fc8217661f25f8ce77c877593f72e1d56f1592de) before unmapping the file, please tell me if it fixes the issue with the last version of [ipf_unpack.exe](https://github.com/r1emu/IPFUnpacker/blob/master/ipf_unpack.exe) I just pushed.

**Comment by pedrobullo** [comment]
Tried from another computer with Windows 8.1. Still no success. There's any pre-requisite like MS SDK? Thank you for these updates btw.

**Comment by Spl3en** [comment]
There's no pre-requisite. It only needs MSVCRT.dll that should be in your C:/Windows/system32 path. I just tested with a Windows 8.1 and it works fine for me.

I just added some more few paranoid checks in case of something weird happens, I suggest you to try again.

Could you give me the md5sum of the test.ipf provided in the repository before and after using `ipf_unpack.exe` ?

Mine is :             

```
  --> md5sum.exe test.encrypt.ipf     # before                  
724dd228ea2296121334928e38add940 *test.encrypt.ipf      
  --> md5sum.exe test.ipf             # after             
6a0f35f10909779c2becdb50b84d2afd *test.ipf             
```

**Comment by pedrobullo** [comment]
Before: 724DD228EA2296121334928E38ADD940
After: 6A0F35F10909779C2BECDB50B84D2AFD

Working for most of files! I guess it's working since beginning (My fault sorry!). But *.ies files still encrypted. Can you try with "ies.ipf"?

**Comment by Spl3en** [comment]
It works fine for me with ies.ipf with the last version.
- Please make sure you're opening the correct file in IPF Suite. (happened to me multiple times to mix up the IPFs thinking I was in the correct folder :blush:)
- Before decrypting it, please make sure your IPF isn't opened in IPF Suite and your game is closed (no Client_tos.exe in the background).

md5sum for IES.IPF **encrypted** : (patch 20939_001001)
ab7ea22bb2d7c0098c1cf3b8c26b6b4d *ies.ipf

md5sum for IES.IPF **decrypted** : 
a586e1c7e3f1499fc29afe69e97cf84b *ies.ipf

![Decrypt IES.IPF](http://i.imgur.com/RHYrQuG.gif)

**Comment by pedrobullo** [comment]
Decrypting from ToS folder solved to me. Multiple IPF's issue, sure. Working fine now. Thank you :dancer:

**Comment by Spl3en** [comment]
Glad it worked :relaxed:
