### ISSUE TITLE
Unable to build in x86

### ISSUE THREAD

**Issue by corexs7** [r1emu/IPFUnpacker#10]
Hello,

I get this error when doing make release

LONG WINAPI crashHandler(EXCEPTION_POINTERS *ExceptionInfo) {
    die("Application crashed at %p. Exception code = %x",
         ExceptionInfo->ContextRecord->Rip, ExceptionInfo->ExceptionRecord->ExceptionCode);

As I understand, this is a crash handler for x86 OS? 
Can the unpacker be build in that version at all? I haven't been able to find any working unpacker for 32 bits systems...

**Comment by Spl3en** [comment]
You can patch the code easily : change Rip to Eip (x86 register) and you should be fine.
