### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by timogasda** [r1emu/IPFUnpacker#3]
Would be cool if this worked on OS X. I'm currently getting this error when compiling:

> ➜  IPFUnpacker git:(master) make release
> /Applications/Xcode.app/Contents/Developer/usr/bin/make release -C src/ipf_unpack
> clang: warning: -Wl,-rpath: 'linker' input unused
> clang: warning: -Wl,/lib: 'linker' input unused
> clang: warning: argument unused during compilation: '-MMD'
> clang: warning: argument unused during compilation: '-s'
> clang: warning: argument unused during compilation: '-L/lib'
> clang: warning: argument unused during compilation: '-s'
> In file included from ies.c:15:
> In file included from ../common/dbg/dbg.h:173:
> /usr/include/ucontext.h:43:2: error: The deprecated ucontext routines require _XOPEN_SOURCE to be defined
> # error The deprecated ucontext routines require _XOPEN_SOURCE to be defined
> 
>  ^
> 1 error generated.
> make[1]: **\* [ies.o] Error 1
> make: **\* [release] Error 2

**Comment by Spl3en** [comment]
I don't have an OSX so I can't test it, but it should work too with few tweaks as it compiles on Linux.
Could you try to add :

> -D_XOPEN_SOURCE=600

At [this](https://github.com/r1emu/IPFUnpacker/blob/master/src/ipf_unpack/Makefile#L18) line, before the -D_GNU_SOURCE, make clean && make release again and tell me if it changed anything?

**Comment by timogasda** [comment]
Now I am getting a bunch of compiler errors. It looks like its using clang, how do I change it to use gcc ?

**Comment by timogasda** [comment]
Okay I think the issue is that "gcc" under OS X is actually `clang`, an LLVM compiler. This compiler does not accept some of the stuff you are using in your code. One thing is the nested function `sortColumns` - which are a non-standard gcc extension btw - but that can be easily fixed. 

However, you are also using a lot of "variable lengths arrays", and clang does not support that:

> ies.c:127:21: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
>                     IesCell (cellOpt->size, cellStr->size) *cell = calloc (1, sizeof (IesCell (cellOpt->size, cellStr->size)));
> 
> ies.c:127:87: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
> ./ies.h:66:18: note: expanded from macro 'IesCell'
>             char value[_strSize + 1];

**Comment by Spl3en** [comment]
Indeed, I'm using GCC extensions heavily, I don't see other solution than installing GCC on OSX for compiling this project.
I don't plan porting it to other compilers, if you want to pull request a portable version, I would merge the code with pleasure.
If you have already it installed, do `export CC=gcc`before launching `make`.

**Comment by ASMtrix** [comment]
yeah it says the array sizing by a variable or function will never be supported by clang unless you want to put exactly the size somehow or guess a size.
I was able to compile this on arch linux by declaring a size for a variable.
