### ISSUE TITLE
iTOS password

### ISSUE THREAD

**Issue by timogasda** [r1emu/IPFUnpacker#4]
I cannot extract any IPF files from the current iTOS client on steam. Do you know if they use a different password?

This is the output when trying to extract global.ipf:

> [ipf_unpack.c:286 in main] Parsing IPF 'test.ipf' (extract) ...
> [zlib.c:91 in zlibDecompress] [ERROR] Can't decompress. Error : -3
> [ipf_unpack.c:172 in process_ipf] [ERROR] Cannot decompress 'addon/token/token.lua'.
> [ipf.c:74 in ipf_read] [ERROR] callback failed for 'global.ipf:addon/token/token.lua'
> [zlib.c:91 in zlibDecompress] [ERROR] Can't decompress. Error : -3
> [ipf_unpack.c:172 in process_ipf] [ERROR] Cannot decompress 'addon/token/token.xml'.
> [ipf.c:74 in ipf_read] [ERROR] callback failed for 'global.ipf:addon/token/token.xml'
> [zlib.c:91 in zlibDecompress] [ERROR] Can't decompress. Error : -3
> [ipf_unpack.c:172 in process_ipf] [ERROR] Cannot decompress 'ui/uixml/controlset.xml'.
> [ipf.c:74 in ipf_read] [ERROR] callback failed for 'global.ipf:ui/uixml/controlset.xml'
> [ipf_unpack.c:299 in main] Done!

**Comment by Spl3en** [comment]
Interesting. They probably changed the format, I haven't looked it yet. I'll look into it and fix it soon.

**Comment by timogasda** [comment]
My guess is that they only changed the password.
Thanks for looking into it

**Comment by Spl3en** [comment]
I've tried decrypting files from files downloaded on Steam (I made sure I had the last version), the files are decrypted well for me.

I think it is a bug with zlib, I was using it very weirdly (with weird deflateInit2 parameters, I copied those used in the client), but the default parameters with deflateInit works too and should be more portable.

I've pushed the changes, please try recompiling everything, decrypt&extract.

**Comment by timogasda** [comment]
Now it's working, thanks :)
