### ISSUE TITLE
Step by step instructions

### ISSUE THREAD

**Issue by Crashic** [r1emu/IPFUnpacker#5]
please do step by step instructions for windows .... already tried everything does nepoluchaetsya :( I beg you.

**Comment by Spl3en** [comment]
Hey,

I'll add a INSTALL file in few days.
I'm on smartphone and I don't have any computer at the moment. If you want a quick howto:
Install MSYS2
Install gcc / make (pacman -S gcc make)
Type make in the root folder
There may be dependencies ; install them too (still woth pacman)
The project should compile correctly with the correct depandencies
