### ISSUE TITLE
GUI interface

### ISSUE THREAD

**Issue by aristides86** [r1emu/IPFUnpacker#7]
Hello Spl3en,

Could you kindly make a windows version for non-programmers with a simple graphical interface? The compiled version of the unpacker gives the 0xc000007b error and I tried to replicate the shown compilation process with no luck. I simply don't understand how it works. GUI would've been a great help.

Thank you!

**Comment by Spl3en** [comment]
You got this error because you're missing a DLL (msvcrt.dll), because you haven't installed the correct Visual C++ Redistribuable.
https://www.microsoft.com/en-us/download/details.aspx?id=48145

I don't plan to make a GUI interface.

**Comment by aristides86** [comment]
Thank you for reply! I reinstalled VC++ from your link. It didn't fix the problem but on another computer it gives another error about missing zlib1.dll Is it also related to VC++?

**Comment by Spl3en** [comment]
No, zlib1 is a dependancy you can install using msys2, or download it here (in the "bin" folder) : https://sourceforge.net/projects/gnuwin32/files/zlib/1.2.3/zlib-1.2.3-bin.zip/download?use_mirror=heanet&download=

**Comment by aristides86** [comment]
I installed msys2 and used the "pacman -S gcc make zlib-devel" command as stated in description as admin. It still asks for zlib1.dll. Then if I directly copy the dll into the folder with the program or into system32 folder it gives the 0xc000007b error.

Anyway, I hope this will resolve in the future. Please keep doing what you're doing for the TOS community we all appreciate it a lot. This has nothing to do with the GUI request so I will close it for now.

Thank you!

**Comment by Spl3en** [comment]
0xc000007b means "STATUS_INVALID_IMAGE_FORMAT" 

> 0xC000007B
> STATUS_INVALID_IMAGE_FORMAT
> {Bad Image} %hs is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support.

Try installing different Visual C++ redistributable. It is an issue related to it.

I'll make a fresh Windows install and include all the dependancies in the next release, thanks for reporting this issue.

**Comment by BlaXun** [comment]
Can u distirbute a compiled version please? I have trouble gettin this to run :(

**Comment by Spl3en** [comment]
Sure, you'll find one in the [release](https://github.com/r1emu/IPFUnpacker/releases) section. Version 1.3 should work.

**Comment by BlaXun** [comment]
Oh god thank u :D 
I just got it to compile anyway XD but thank u :)
