### ISSUE TITLE
No rule to make target "..."

### ISSUE THREAD

**Issue by lucianowi** [r1emu/IPFUnpacker#8]
Win10 here: http://i.imgur.com/OvQvlzs.png

**Comment by Spl3en** [comment]
You need to change directory (`cd` command) to the IPFUnpacker source directory before using `make`.

For instance : 

``` bash
git clone https://github.com/r1emu/IPFUnpacker.git
cd IPFUnpacker
make clean && make release
```

**Comment by lucianowi** [comment]
where should I put the IPFUnpacker folder to this command works? sry, im newb, and ty for answer. @Spl3en

**Comment by Spl3en** [comment]
Anywhere you want.

Try copy/pasting the 3 previous commands anywhere you want. If you haven't used git before, you may need to install it (`pacman -S git`).
I'll complete the installation steps.
