### ISSUE TITLE
Having error when make file

### ISSUE THREAD

**Issue by venustan** [r1emu/IPFUnpacker#9]
Hi,

I'm hitting error during "make release". Below is the error log:
`xubuntos2@xubuntos2-desktop:~/Desktop/IPF Suite/IPFUnpacker-master$ make clean && make release
make clean -C src/ipf_unpack
make[1]: Entering directory`/home/xubuntos2/Desktop/IPF Suite/IPFUnpacker-master/src/ipf_unpack'
-e Cleaning ...
make[1]: Leaving directory `/home/xubuntos2/Desktop/IPF Suite/IPFUnpacker-master/src/ipf_unpack'
make release -C src/ipf_unpack
make[1]: Entering directory`/home/xubuntos2/Desktop/IPF Suite/IPFUnpacker-master/src/ipf_unpack'
cc: -rpath: linker input file unused because linking not done
cc: /lib: linker input file unused because linking not done
-e Compiling 'ipf_unpack.c'
In file included from ipf_unpack.c:16:
../common/crc32/crc32.h:22:47: warning: no newline at end of file
In file included from ipf_unpack.c:17:
../common/fs/fs.h:38:26: warning: no newline at end of file
In file included from ipf_unpack.c:18:
../common/zlib/zlib.h:19:18: error: zlib.h: No such file or directory
ipf_unpack.c: In function 'process_ipf':
ipf_unpack.c:191: error: 'PATH_MAX' undeclared (first use in this function)
ipf_unpack.c:191: error: (Each undeclared identifier is reported only once
ipf_unpack.c:191: error: for each function it appears in.)
ipf_unpack.c:192: warning: unused variable 'targetFullName'
ipf_unpack.c:191: warning: unused variable 'targetPath'
ipf_unpack.c:307:2: warning: no newline at end of file
make[1]: **\* [ipf_unpack.o] Error 1
make[1]: Leaving directory `/home/xubuntos2/Desktop/IPF Suite/IPFUnpacker-master/src/ipf_unpack'
make: *** [release] Error 2
`

**Comment by Spl3en** [comment]
```
../common/zlib/zlib.h:19:18: error: zlib.h: No such file or directory
```

You need to install zlib1g-dev, such as :

```
$ sudo apt-get install zlib1g-dev
```

---

```
 ipf_unpack.c:191: error: 'PATH_MAX' undeclared (first use in this function)
```

Fixed on master, please git pull. Thanks

**Comment by venustan** [comment]
Thanks for your response. But I'm have error when installing zlib1g-dev. Not sure is it because of I'm using Xubuntu in Oracle VM VirtualBox. (In a condition when Internet is working fine in the virtual machine)

```
xubuntos2@xubuntos2-desktop:~/Desktop/IPF Suite/IPFUnpacker-master$ sudo apt-get install zlib1g-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  mysql-common libmysqlclient15off
Use 'apt-get autoremove' to remove them.
The following NEW packages will be installed:
  zlib1g-dev
0 upgraded, 1 newly installed, 0 to remove and 271 not upgraded.
Need to get 160kB of archives.
After this operation, 385kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  zlib1g-dev
Install these packages without verification [y/N]? y
**Err http://gb.archive.ubuntu.com hardy/main zlib1g-dev 1:1.2.3.3.dfsg-7ubuntu1
  404 Not Found [IP: 91.189.88.149 80]
Failed to fetch http://gb.archive.ubuntu.com/ubuntu/pool/main/z/zlib/zlib1g-dev_1.2.3.3.dfsg-7ubuntu1_i386.deb  404 Not Found [IP: 91.189.88.149 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?**

```

I had pull again the ipf_unpack.c, but still have error when make release. Not sure is it because of my zlib1g-dev is not installed correctly:

```
xubuntos2@xubuntos2-desktop:~/Desktop/IPF Suite/IPFUnpacker-master$ make clean && make release
make clean -C src/ipf_unpack
make[1]: Entering directory `/home/xubuntos2/Desktop/IPF Suite/IPFUnpacker-master/src/ipf_unpack'
-e Cleaning ...
make[1]: Leaving directory `/home/xubuntos2/Desktop/IPF Suite/IPFUnpacker-master/src/ipf_unpack'
make release -C src/ipf_unpack
make[1]: Entering directory `/home/xubuntos2/Desktop/IPF Suite/IPFUnpacker-master/src/ipf_unpack'
cc: -rpath: linker input file unused because linking not done
cc: /lib: linker input file unused because linking not done
-e Compiling 'ipf_unpack.c'
In file included from ipf_unpack.c:16:
../common/crc32/crc32.h:22:47: warning: no newline at end of file
In file included from ipf_unpack.c:17:
../common/fs/fs.h:38:26: warning: no newline at end of file
In file included from ipf_unpack.c:18:
../common/zlib/zlib.h:19:18: error: zlib.h: No such file or directory
make[1]: *** [ipf_unpack.o] Error 1
make[1]: Leaving directory `/home/xubuntos2/Desktop/IPF Suite/IPFUnpacker-master/src/ipf_unpack'
make: *** [release] Error 2
```

**Comment by venustan** [comment]
Wait, I'm in the University, error above might caused by proxy server in the University. I will try again at home.

**Comment by Spl3en** [comment]
Also, make sure to sudo apt-get update as indicated.

**Comment by venustan** [comment]
When try to install zlib1g-dev, error below occurred:

```
xubuntos2@xubuntos2-desktop:~/Desktop/IPF Suite/IPFUnpacker-master$ sudo apt-get install zlib1g-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run `apt-get -f install' to correct these:
The following packages have unmet dependencies:
  libc6-dev: Depends: libc6 (= 2.7-10ubuntu4) but 2.19-10ubuntu2.3 is to be installed
  zlib1g-dev: Depends: zlib1g (= 1:1.2.8.dfsg-1ubuntu1) but 1:1.2.3.3.dfsg-7ubuntu1 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

Seem like the xubuntos2 which im using is old version. But hitting error also when "apt-get -f install". 

```
... ...
Stopping some services possibly affected by the upgrade (will be restarted later):
  cron: stopping...done.

No packages found matching libc-bin.
dpkg: error processing /var/cache/apt/archives/libc6_2.19-10ubuntu2.3_i386.deb (--unpack):
 subprocess pre-installation script returned error exit status 1
/var/lib/dpkg/tmp.ci/postrm: 53: dpkg-maintscript-helper: not found
dpkg: error while cleaning up:
 subprocess post-removal script returned error exit status 127
Errors were encountered while processing:
 /var/cache/apt/archives/libc-dev-bin_2.19-10ubuntu2.3_i386.deb
 /var/cache/apt/archives/binutils_2.24.90.20141014-0ubuntu3.1_i386.deb
 /var/cache/apt/archives/make_4.0-8_i386.deb
 /var/cache/apt/archives/libc6-dev_2.19-10ubuntu2.3_i386.deb
 /var/cache/apt/archives/libc6_2.19-10ubuntu2.3_i386.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I'm still figuring how to resolve this issue. Even I removed libc6_2.19-10ubuntu2.3_i386.deb and re-download also the same. I did the upgrade, also same.

**Comment by Spl3en** [comment]
There's something weird with your package installation. One or multiple of your packages are bad installed or your distribution is too old. Install the last version of your distribution. zlib-devel should be a very easy package to install, so there's really something wrong.

Don't forget you can use Windows to compile the project if you wish! https://github.com/r1emu/IPFUnpacker/blob/master/INSTALL.md
